{% set version = "2.0-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iswr
  version: {{ version|replace("-", "_") }}

source:
  fn: ISwR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ISwR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ISwR/ISwR_{{ version }}.tar.gz
  sha256: eabbe6346930bf0a30d5718cd7446ca389db1d83bc09c41732982b64943d5ead

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('ISwR')"           # [not win]
    - "\"%R%\" -e \"library('ISwR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ISwR
  license: GPL (>= 2)
  summary: 'Data sets and scripts for text examples and exercises in  P. Dalgaard (2008), `Introductory
    Statistics with R'', 2nd ed., Springer Verlag, ISBN 978-0387790534.  '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
