appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: tyiCHp7Sm5qME2ELd0QiarnAMi3Y1XIS1xNtludLVlfwMz9YFyHSB5qmDli/hMUx7dOWU1cJv9Jb9my0tp1AK1TqbO31/rLZNmYrhn6YK51slzakgj2v+bs5uW/To+iyshhHnKCjKjSUCMVnYyHqRjYXuUWRYpAH4oBD11cZ6sd19Pk+wPidRj/ufJqDABIHS+xC9+uwFxqkhCcVkkH1hiww/Z4WuC0ByXvpZHP0wIsj1W3vUG9wiK92oZkIt1nz6vEevuLi8/u8ehUMDndj2nu0Up3n2xgxlvu/YR6ug7Jf9l2Lhi90HzlwMcYz7Ry1kiWgB1IUSxvNIidL+2wSqntLN1RN4dynSQ5ek1FwAVfxuqYu4gpIvQe/YJjQf3QvTmU/HDFUkvlBxQfyv5nNn8oq+2DhUPy8RVHOiZml5u8/IiM76OArUdO8QhPMTx8zesef7bLUNsFWG+667wKsprcj/0y0jezyAJJwc79rfR8+rD1pRxOPm1V3m1MNuZ+MWOWYtma3rCblnu+TsKzqygJW8lVLlAKLDunJi05hhu7QV9Kjtyv0TPPLzDBuQxxuvHVPKz/IYcHFCPKYtKgMXp8EMIk9YRiK7BswQOAeAXDMmYy6hjkWZsuegG9iEDKo3p4BMnvSTG/70PIlTo6MQlcS7xVzwd67Hgo3/3nP3B8=
conda_forge_output_validation: true
